version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: go/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000

  web:
    build:
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - api